import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Github } from "lucide-react";
import { headers } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { CookieBanner } from "@/components/cookie-banner";
import { QueryProvider } from "@/components/query-provider";
import { AuthProvider } from "@/contexts/auth-context";

const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  title: "SkinBaron-Tracker",
  description: "Monitor CS2 skins on SkinBaron with custom alerts and Discord notifications",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the per-request CSP nonce generated by proxy.ts
  const nonce = (await headers()).get('x-nonce') ?? '';

  // Skip SSR session check - cookies are cross-subdomain and client will handle auth
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          nonce={nonce}
        >
          <AuthProvider initialAuth={undefined}>
            <QueryProvider>
              <div className="min-h-screen bg-background flex flex-col">
                <main className="flex-1">
                  {children}
                </main>
                <footer className="border-t border-border/40 bg-muted/20">
                  <div className="container mx-auto px-4 py-4 text-[13px] text-muted-foreground flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <span>&copy; 2026 SkinBaron Tracker</span>
                    <div className="flex items-center gap-5">
                      <Link className="hover:text-foreground transition-colors" href="/tos">Terms</Link>
                      <Link className="hover:text-foreground transition-colors" href="/privacy">Privacy</Link>
                      <a 
                        href="https://github.com/Oswaaaald" 
                        target="_blank" 
                        rel="noopener noreferrer" 
                        className="hover:text-foreground transition-colors flex items-center gap-1.5"
                      >
                        <Github className="h-3.5 w-3.5" />
                        GitHub
                      </a>
                    </div>
                  </div>
                </footer>
              </div>
              <Toaster />
              <CookieBanner />
            </QueryProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
