import pg from 'pg';
import { drizzle, NodePgDatabase } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import * as schema from './schema.js';
import { appConfig } from '../lib/config.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pool = new pg.Pool({
  connectionString: appConfig.DATABASE_URL,
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 5000,
});

export const db = drizzle(pool, { schema });

export type AppDatabase = NodePgDatabase<typeof schema>;

/**
 * Run Drizzle migrations on startup — creates/updates tables as needed.
 * Uses the SQL files generated by `drizzle-kit generate`.
 */
export async function initializeDatabase(): Promise<void> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  // In compiled dist: dist/database/connection.js → drizzle/ is at ../../drizzle
  const migrationsFolder = path.resolve(__dirname, '..', '..', 'drizzle');
  await migrate(db, { migrationsFolder });
}

export async function closeDatabase(): Promise<void> {
  await pool.end();
}

/**
 * Check database connectivity (used by health checks)
 */
export async function checkDatabaseHealth(): Promise<boolean> {
  try {
    const client = await pool.connect();
    try {
      const result = await client.query('SELECT 1 as test');
      return result.rows[0]?.test === 1;
    } finally {
      client.release();
    }
  } catch {
    return false;
  }
}
